### ISSUE TITLE
stop and shop busted.

### ISSUE THREAD

**Issue by jgdf42** [primaryobjects/grocery-digital-coupons#5]
shoprite works, stop and shop won't launch.

```
c:\Users\ThinkCentre\Downloads\grocery-digital-coupons-master>client.py --store stop_and_shop
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Requirement already satisfied: PyJWT in c:\users\thinkcentre\appdata\local\programs\python\python311\lib\site-packages (2.8.0)

[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "C:\Users\ThinkCentre\Downloads\grocery-digital-coupons-master\client.py", line 37, in <module>
    grocery_coupons.stop_and_shop(email, password, phone, delay, onStatus)
  File "C:\Users\ThinkCentre\Downloads\grocery-digital-coupons-master\grocery_coupons.py", line 264, in stop_and_shop
    email = parser.get('stop and shop', 'email')
            ^^^^^^
NameError: name 'parser' is not defined
Exception ignored in: <function Chrome.__del__ at 0x0000018C331DCEA0>
Traceback (most recent call last):
  File "C:\Users\ThinkCentre\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 843, in __del__
  File "C:\Users\ThinkCentre\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 798, in quit
OSError: [WinError 6] The handle is invalid
```

**Comment by primaryobjects** [comment]
Thank you for the notice. Please feel free to fork to create an update. Thanks!
